version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assignment 
    ports:
     - "3308:3306"
    networks:
      - springboot-mysql-network

  app:
    image: beingsourabh/spring-backend:latest
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/assignment
       SPRING_DATASOURCE_USERNAME: root
       SPRING_DATASOURCE_PASSWORD: root
    depends_on: 
      - mysql-db  
    networks:
      - springboot-mysql-network
    
  frontend:
    image: beingsourabh/react-frontend:latest
    container_name: react-frontend
    ports:
     - "3000:80"
    depends_on:
     - app
    networks:
     - springboot-mysql-network  	  

networks:
  springboot-mysql-network:
    driver: bridge
